### ISSUE TITLE
Docker Image

### ISSUE THREAD

**Issue by paweljacewicz** [do-web/e2ee-cloud-server#1]
Hi!

It would be really useful if you can create a Dockerfile (or docker-compose.yml) with the working environment. It would be beneficial for UA testing as for now I'm struggling with setting proper environment to run the project.

Thanks!
Pawel

**Comment by do-web** [comment]
Thanks for your comment, as soon as I have time, I will provide a docker file.

**Comment by paweljacewicz** [comment]
Super! Thanks for that!

**Comment by do-web** [comment]
I have added a docker file.

**Comment by paweljacewicz** [comment]
Super! Thanks! I'll try to test it ASAP.
