### ISSUE TITLE
Unable to make it works

### ISSUE THREAD

**Issue by W0rmsy** [do-web/e2ee-cloud-server#5]
Hello, I've tried multiple ways to run e2ee-coud and all of them failed.

- The bundle on one of my server: 
When I reach the URL I'm directly asked for the master password (no basic auth) and when I provide it I'm arriving on a page with the ability to search or log out. Under the name there is a spinning blue ring and after some time it asks again for the master password.
By looking in my apache2 logs I can see that;
"GET /config HTTP/1.1" 404 490
"GET /filesystems HTTP/1.1" 404 490 

- I tried then the docker version
Error 500
e2ee-cloud-php-fpm | NOTICE: PHP message: PHP Warning:  require(/application/vendor/autoload.php): failed to open stream: No such file or directory in /application/config/bootstrap.php on line 5
e2ee-cloud-php-fpm | NOTICE: PHP message: PHP Fatal error:  require(): Failed opening required '/application/vendor/autoload.php' (include_path='.:/usr/share/php') in /application/config/bootstrap.php on line 5

- so I tried the docker version with the bundle (which contains the vendor)
Error 500
e2ee-cloud-php-fpm | NOTICE: PHP message: PHP Fatal error:  Uncaught Symfony\Component\Dotenv\Exception\PathException: Unable to read the "/application/.env" environment file. in /application/vendor/symfony/dotenv/Dotenv.php:465
e2ee-cloud-php-fpm | Stack trace:
e2ee-cloud-php-fpm | #0 /application/vendor/symfony/dotenv/Dotenv.php(50): Symfony\Component\Dotenv\Dotenv->doLoad(false, Array)
e2ee-cloud-php-fpm | #1 /application/vendor/symfony/dotenv/Dotenv.php(70): Symfony\Component\Dotenv\Dotenv->load('/application/.e...')
e2ee-cloud-php-fpm | #2 /application/config/bootstrap.php(15): Symfony\Component\Dotenv\Dotenv->loadEnv('/application/.e...')
e2ee-cloud-php-fpm | #3 /application/public/index.php(7): require('/application/co...')
e2ee-cloud-php-fpm | #4 {main}
e2ee-cloud-php-fpm |   thrown in /application/vendor/symfony/dotenv/Dotenv.php on line 465

- Last test: fresh install of Apache2, PHP, composer, etc...
downloaded the latest release from GitHub, installed the dependencies with composer and same bhevior... no basic auth, directly asks passphrase and when provided, do nothing expect spinning
==> /var/log/apache2/access.log <==
127.0.0.1 - - [06/Dec/2019:20:55:33 +0100] "GET /config HTTP/1.1" 404 490 "http://localhost:8080/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:70.0) Gecko/20100101 Firefox/70.0"
127.0.0.1 - - [06/Dec/2019:20:55:39 +0100] "GET /filesystems HTTP/1.1" 404 490 "http://localhost:8080/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:70.0) Gecko/20100101 Firefox/70.0"

In all th tests, I linked the document root to the public dir

**Comment by do-web** [comment]
Hi,
have you read the readme? You must run composer install first then the require(/application/vendor/autoload.php) should be available.

Maybe its a Windows problem, so use docker or a linux distribution
